import assert from'node:assert/strict';import{recoverSource,rescueZeroSelection,classifyShortfall,validateBroadcastAudit}from'./source-recovery.mjs';
const base={topicKey:'eye',title:'눈 건강',optimizedTitle:'눈 건강 검사',community:'SBS',searchIntent:'검사',url:'https://community.invalid/post',publishedAt:'2026-08-31T09:00:00+09:00',ageHours:27,viewsCollected:false,views:null,platformRank:1,platformRankPercentile:1,topicSignalPercentile:.9,engagementEvidenceType:'방송 편집 1위',sourceBodyVerified:false,synopsisVerified:true,factOpinionSeparated:true,reactionsVerified:true,synopsis:'공식 방송에서 눈 건강과 검사 필요성을 다룬 회차의 방송사, 프로그램명, 회차, 방송일과 주요 내용을 확인했습니다. 개인 증상을 진단으로 단정하지 않고 국내 공식 자료와 연결한 검증 줄거리입니다.',reactions:['공식 회차 확인','조회 미수집'],directHealthLinkScore:8,titleIntroMatchScore:4,bodyReconnectScore:3,searchSolutionScore:10,officialEvidenceScore:5,fruitkingUspScore:3,officialEvidence:[{},{},{}],articleFile:'x',keywords:['눈','검사'],hashtags:['#1','#2','#3','#4','#5','#6'],sourceKind:'broadcast',broadcaster:'SBS',programName:'좋은아침',episode:'7328회',broadcastDate:'2026-08-31'};
const recoverable={...base,sourceAttempts:[{type:'direct',url:base.url,reachable:false,bodyVerified:false,sameTopic:true},{type:'official-program',url:'https://programs.sbs.co.kr/vod/1',reachable:true,bodyVerified:true,sameTopic:true,reactionsVerified:true}]};
assert.equal(recoverSource(recoverable).recoveryStatus,'recovered','커뮤니티 실패 뒤 공식 방송 원문으로 복구');
const rescued=rescueZeroSelection([], [recoverable]);assert.equal(rescued.recoveryRun,true);assert.equal(rescued.selected.length,1,'0편 재탐색 뒤 1편 복구');
const failed=rescueZeroSelection([], [{...recoverable,sourceAttempts:recoverable.sourceAttempts.map(x=>({...x,reachable:false,bodyVerified:false}))}]);assert.equal(failed.selected.length,0,'모든 대체 원문 실패 시 정상 0편');
assert.equal(classifyShortfall({...base,sourceKind:undefined,sourceReachable:false,sourceAttempts:undefined}),'원문 접근 실패');
assert.equal(validateBroadcastAudit({...base,views:null}),true);assert.throws(()=>validateBroadcastAudit({...base,views:999}),/BROADCAST_VIEW_ESTIMATE_FORBIDDEN/);
console.log('source recovery regression tests passed');
