import assert from'node:assert/strict';
import path from'node:path';
import{buildWeeklyInsights,renderWeeklyInsights}from'./weekly-insights.mjs';
const result=buildWeeklyInsights('2026-08-30',path.resolve('.'));
assert.equal(result.communityDays,2);
assert.equal(result.healthDays,1);
assert.equal(result.completeDays,1);
assert.equal(result.phase,'관찰 중');
assert.ok(result.uniqueEvents>0);
assert.ok(result.keywords.length>0);
assert.ok(result.themes.length>0);
assert.ok(result.keywords.every(x=>x.urls.length<=3&&x.state));
assert.ok(result.themes.every(x=>['리포트 동시 등장','편집 보완'].includes(x.origin)));
const html=renderWeeklyInsights(result);
assert.match(html,/커뮤니티 2\/7일 · 건강주제 1\/7일 · 통합 1\/7일/);
assert.match(html,/관찰 키워드/);
assert.match(html,/중복 제거 후 근거/);
console.log(`weekly insights tests passed: ${result.keywords.length} keywords, ${result.themes.length} themes, ${result.uniqueEvents} unique events`);
